version: '3'


services:

  admin:
    build:
      context: ./frontend/admin
    ports:
      - "4000:80"
    networks:
      - app-network

  customer:
    build:
      context: ./frontend/customer
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000" 
    environment:
      - MONGO_URL=mongodb+srv://admin:admin123@phoneshop.7zyrd.mongodb.net/?retryWrites=true&w=majority&appName=PhoneShop
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
