# Sử dụng Node.js image chính thức
FROM node:16

# Set working directory trong container
WORKDIR /usr/src/app

# Sao chép các file package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Expose cổng mà backend Node.js của bạn sẽ chạy (ví dụ, cổng 5000)
EXPOSE 5000

# Lệnh để chạy ứng dụng Node.js (giả sử file chính là server.js)
CMD ["node", "server.js"]
