# Dockerfile for Admin ReactJS

# Step 1: Build the React app
FROM node:16 AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .

# Build the React app (for Admin)
RUN npm run build

# Step 2: Serve the React app with Nginx
FROM nginx:alpine

# Expose port 4000 for Admin
EXPOSE 4000

# Copy build files to Nginx's public directory
COPY --from=build /app/build /usr/share/nginx/html

# Start Nginx to serve the built React app
CMD ["nginx", "-g", "daemon off;"]
